#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

cookbook 'nodejs',
  :git => 'https://github.com/mdxp/nodejs-cookbook'

cookbook 'postgresql',
  :git => 'https://github.com/phlipper/chef-postgresql'

cookbook 'ruby_build',
  :git => 'https://github.com/fnichol/chef-ruby_build',
  :ref => 'v0.8.0'

cookbook 'rbenv',
  :git => 'https://github.com/ajsharma/chef-rbenv',
  :ref => 'v0.7.2'
